EudiReferenceWallet.xcodeproj/project.pbxproj, fastlane/Fastfile, fastlane/README.md
=> Automated Application Versioning via Fastlane

Modules/logic-business/Sources/DI/DIGraph.swift
=> Minor cleanup

README.md
=> [fix] updated module diagram in readme

Modules/feature-common/Sources/UI/Component/DocumentDetailsHeaderView.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Cell/DocumentCellView.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Model/DocumentUIModel.swift, Modules/feature-dashboard/Tests/Interactor/TestDashboardInteractor.swift, Modules/feature-issuance/Sources/UI/Document/Details/DocumentDetailsView.swift, Modules/feature-issuance/Sources/UI/Document/Details/Model/DocumentDetailsUIModel.swift, Modules/logic-business/Sources/Extension/Locale+Extensions.swift, Modules/logic-core/Sources/Extension/MdocDecodable+Extensions.swift, Modules/logic-resources/Sources/Extension/Text+Extensions.swift, Modules/logic-resources/Sources/LocalizableString.swift, Modules/logic-resources/Sources/Resources/Localizable.xcstrings
=> Documentation Expiration UI Indicator

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> Wallet-Kit update

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> New Wallet kit version

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-issuance/Sources/UI/Document/Add/AddDocumentView.swift, Modules/feature-issuance/Sources/UI/Document/Add/AddDocumentViewModel.swift, Modules/logic-core/Package.swift, Wallet/Config/WalletDemo.xcconfig, Wallet/Config/WalletDemoRelease.xcconfig
=> [fix] updated wallet kit

Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-resources/Sources/Resources/Localizable.xcstrings
=> Minor correction

Modules/feature-login/Sources/UI/Welcome/WelcomeLocators.swift, Modules/feature-login/Sources/UI/Welcome/WelcomeView.swift, Modules/logic-ui/Sources/DesignSystem/Component/Type/AccesibilityLocatorViewModifier.swift
=> [fix] accessibility locator

Modules/logic-resources/Sources/Resources/Localizable.xcstrings
=> Removed unused localizations

Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Sources/UI/Document/Offer/DocumentOfferViewModel.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
=> Mock generation for previous changes

Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-assembly/Sources/Router/RouterHost.swift, Modules/logic-ui/Sources/Config/ConfigUiLogic.swift, Modules/logic-ui/Sources/Controller/DeepLinkController.swift, Modules/logic-ui/Sources/Navigation/RouterContract.swift, Modules/logic-ui/Tests/Controller/TestDeepLinkController.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
=> Refactored some function names and logic to make it clearer

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> New Core Version to support IssuerSigned

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift
=> Sync with Wallet-Kit 0.4.4 Storage changes

Modules/logic-core/Sources/Controller/WalletKitController.swift
=> Correction

Wallet/Config/WalletDemo.xcconfig, Wallet/Config/WalletDemoRelease.xcconfig, Wallet/Config/WalletDev.xcconfig, Wallet/Config/WalletDevRelease.xcconfig
=> new vci identifier

Wallet/Config/WalletDemo.xcconfig, Wallet/Config/WalletDemoRelease.xcconfig, Wallet/Config/WalletDev.xcconfig, Wallet/Config/WalletDevRelease.xcconfig
=> VCI Client Id 

Wallet/Wallet.plist
=> New openId4VP Schemes

Wallet/Wallet.plist
=> bundle version id plist value

Modules/feature-issuance/Sources/UI/Document/Add/AddDocumentViewModel.swift, Modules/logic-ui/Sources/Controller/DeepLinkController.swift, Wallet/Wallet.plist
=> New credential offer schema

Modules/logic-ui/Sources/Controller/DeepLinkController.swift
=> Fixed issue with credential offer issuance when the wallet is empty

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Config/WalletKitConfig.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Wallet/Config/WalletDemo.xcconfig, Wallet/Config/WalletDemoRelease.xcconfig, Wallet/Config/WalletDev.xcconfig, Wallet/Config/WalletDevRelease.xcconfig, Wallet/Wallet.plist
=> Wallet Kit Update 0.4.8

Wallet/Wallet.plist
=> plist minor refactor

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> Wallet kit update to 0.4.9, fixes for verifier cert chain

Modules/logic-core/Sources/Controller/WalletKitController.swift
=> metada for Age attestation

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> Wallet-Kit update, fixed iOS 15/16 uri parsing for credential offer

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-business/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Sources/Model/RequestItemConvertible.swift, Modules/logic-test/Package.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
=> Upgraded Cuckoo and mock generation

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> Wallet Kit update to support custom URLSession

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Config/WalletKitConfig.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift, README.md, wiki/configuration.md, wiki/how_to_build.md
=> How to build instructions, WalletKit Update, Configuration Corrections

SECURITY.md
=> Update PGP Key link

wiki/how_to_build.md
=> [fix] readme updates

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> New walletkit update

Modules/feature-issuance/Sources/UI/Document/Code/OfferCodeView.swift
=> Minor UI Correction

Modules/logic-assembly/Sources/DI/LogicAssemblyModule.swift, Modules/logic-business/Sources/DI/LogicBusinessAssembly.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-core/Sources/DI/LogicCoreAssembly.swift, Modules/logic-core/Sources/Extension/MdocDecodable+Extensions.swift, Modules/logic-core/Sources/Extension/NameValue+Extensions.swift, Modules/logic-resources/Sources/Resources/Localizable.xcstrings, Modules/logic-ui/Sources/DI/LogicUiAssembly.swift, Modules/logic-ui/Sources/DesignSystem/Component/Wrap/WrapCheckBoxView.swift
=> Various bug fixes, corrections and improvements

Modules/feature-issuance/Sources/UI/Document/Code/OfferCodeView.swift, Modules/logic-resources/Sources/Manager/ImageManager.swift, Modules/logic-resources/Sources/Resources/Images.xcassets/ic-message.imageset/Contents.json, Modules/logic-resources/Sources/Resources/Images.xcassets/ic-message.imageset/ic-message.svg
=> Ui corrections for pre-auth flow

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-test/Package.swift
=> Mocking framework updates

README.md
=> Update readme file according to QA review

README.md, wiki/verifier_proximity.md
=> Verifier proximity readme

Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Sources/Config/WalletKitConfig.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
=> Document storage service name configuration

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Sources/Interactor/DashboardInteractor.swift, Modules/feature-dashboard/Sources/UI/Dashboard/DashboardView.swift, Modules/feature-dashboard/Sources/UI/Dashboard/DashboardViewModel.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-business/Sources/Extension/Date+Extensions.swift, Modules/logic-business/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Config/WalletKitConfig.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-core/Sources/DI/LogicCoreAssembly.swift, Modules/logic-resources/Sources/LocalizableString.swift, Modules/logic-resources/Sources/Manager/ImageManager.swift, Modules/logic-resources/Sources/Resources/Localizable.xcstrings, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
=> Implementation for logs retrieval throught the dashboard modal.

Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Sources/UI/Dashboard/DashboardView.swift, Modules/feature-dashboard/Sources/UI/Dashboard/DashboardViewModel.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-business/Sources/Builder/ArrayBuilder.swift, Modules/logic-business/Tests/Mock/GeneratedMocks.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
=> Improvements for dashboard modal options

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-dashboard/Sources/UI/Dashboard/DashboardView.swift
=> Ui Corrections, Depedency updates

Modules/feature-common/Sources/UI/Request/Model/RequestDataUIModel.swift, Modules/feature-issuance/Sources/Interactor/AddDocumentInteractor.swift, Modules/feature-issuance/Sources/UI/Document/Add/Model/AddDocumentUIModel.swift, Modules/logic-core/Sources/Model/DocumentIdentifier.swift, Modules/logic-resources/Sources/LocalizableString.swift, Modules/logic-resources/Sources/Resources/Localizable.xcstrings
=> Photo id attestation support

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> New WalletKit 0.6.3

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-test/Sources/Utils/Constants.swift, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-core/Sources/Extension/WalletStorage.Document+Extensions.swift, Modules/logic-core/Sources/Model/DeferrredDocument.swift
=> WalletKit update 0.6.6

Modules/feature-common/Sources/Config/ScannerUiConfig.swift, Modules/feature-common/Sources/DI/FeatureCommonAssembly.swift, Modules/feature-common/Sources/Interactor/ScannerInteractor.swift, Modules/feature-common/Sources/UI/Scanner/ScannerView.swift, Modules/feature-common/Sources/UI/Scanner/ScannerViewModel.swift, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-assembly/Sources/Router/RouterHost.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-business/Sources/Validator/FormValidator.swift, Modules/logic-business/Tests/Mock/GeneratedMocks.swift, Modules/logic-business/Tests/Validator/TestFormValidator.swift, Modules/logic-resources/Sources/LocalizableString.swift, Modules/logic-resources/Sources/Resources/Localizable.xcstrings, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
=> Implementation of QR Validation and UI informative message on scan failures for issuance/Presentation

Modules/feature-common/Sources/UI/Scanner/ScannerViewModel.swift, Modules/logic-business/Sources/Validator/FormValidator.swift, Modules/logic-business/Tests/Validator/TestFormValidator.swift
=> improved isValidUrl rule to be configurable for all cases.

Modules/logic-business/Sources/Extension/String+Extensions.swift, Modules/logic-business/Sources/Validator/FormValidator.swift
=> Added extension function to check for String nullability and emptiness.

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift
=> WalletKit Update to 0.6.7

Modules/logic-business/Tests/Validator/TestFormValidator.swift
=> Removed unused function from TestFormValidator

EudiReferenceWallet.xcodeproj/project.pbxproj, Modules/feature-common/Package.swift, Modules/feature-common/Sources/Config/Issuance/IssuanceCodeUiConfig.swift, Modules/feature-dashboard/Package.swift, Modules/feature-dashboard/Sources/UI/Dashboard/DashboardView.swift, Modules/feature-dashboard/Sources/UI/Dashboard/DashboardViewModel.swift, Modules/feature-issuance/Package.swift, Modules/feature-login/Package.swift, Modules/feature-login/Sources/Interactor/FAQsInteractor.swift, Modules/feature-presentation/Package.swift, Modules/feature-proximity/Package.swift, Modules/feature-proximity/Sources/Interactor/ProximityInteractor.swift, Modules/feature-startup/Package.swift, Modules/feature-test/Package.swift, Modules/logic-analytics/Package.swift, Modules/logic-api/Package.swift, Modules/logic-assembly/Package.swift, Modules/logic-authentication/Package.swift, Modules/logic-business/Package.swift, Modules/logic-core/Package.swift, Modules/logic-resources/Package.swift, Modules/logic-resources/Sources/Manager/ShapeManager.swift, Modules/logic-test/Package.swift, Modules/logic-ui/Package.swift, Modules/logic-ui/Sources/Extension/LocalizedStringKey+Extensions.swift, Modules/logic-ui/Sources/Extension/TextField+Extensions.swift
=> Swift 6 support, iOS 18 Support, Min IOS Target is now 16.

Modules/feature-common/Sources/Router/CommonRouter.swift, Modules/feature-common/Sources/UI/QuickPin/QuickPinView.swift
=> Resolved issue with QuickPin Nav Graph

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Sources/Config/WalletKitConfig.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift, Wallet/Config/WalletDemo.xcconfig, Wallet/Config/WalletDemoRelease.xcconfig, Wallet/Config/WalletDev.xcconfig, Wallet/Config/WalletDevRelease.xcconfig, Wallet/Wallet.plist, wiki/configuration.md, wiki/how_to_build.md
- Removed ClientIdScheme.Preregistered configuration due to verifier name extraction from san_dns
- Dependencies update
=> Removed ClientIdScheme.Preregistered configuration due verifier name extraction from san_dns

Modules/feature-common/Sources/UI/Request/BaseRequestViewModel.swift
=> Fixed presentation share data when required fields are not in storage

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> New WalletKit version 0.7.0

.gitignore, EudiReferenceWallet.xcodeproj/project.pbxproj, EudiReferenceWallet.xcodeproj/xcshareddata/xcschemes/EUDI Wallet Demo.xcscheme, EudiReferenceWallet.xcodeproj/xcshareddata/xcschemes/EUDI Wallet Dev.xcscheme, Wallet/Wallet.plist, fastlane/Appfile, fastlane/Fastfile, fastlane/README.md
=> Maintenance (fastlane, target, profiles)

fastlane/Fastfile
=> Reactivated fastlane tagging

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-issuance/Sources/Interactor/DocumentOfferInteractor.swift, Modules/logic-core/Package.swift, Modules/logic-ui/Sources/Controller/DeepLinkController.swift
=> Resolved the issue with the combination of a deferred document that requires Dynamic Authentication

.github/PULL_REQUEST_TEMPLATE.md
=> Updated Pull request template

Modules/feature-issuance/Sources/UI/Document/Code/OfferCodeView.swift
SwiftUI preview fot offer code view.
=> preview for offer code view

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-business/Package.swift
=> SwiftMacroCopyable version update

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-issuance/Sources/UI/Success/DocumentSuccessView.swift, Modules/logic-core/Package.swift
=> New WalletKit version

Modules/feature-proximity/Sources/UI/Connectivity/ProximityConnectionView.swift, Modules/feature-startup/Sources/UI/StartupView.swift
=> Minor change from fileprivate to private

.github/CODEOWNERS
added .md ownership on CODEOWNERS file
=> modified codeowners

.github/PULL_REQUEST_TEMPLATE.md
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the readme
- [] I have added unit tests that prove my fix is effective or that my feature works
- [] I have checked that my views are *accessible*
=> Correction for pull request template

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> Dependencies updates, new wallet kit, new mock generation binary

Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-business/Sources/Config/ConfigLogic.swift, Modules/logic-business/Sources/Config/RQESConfig.swift, Modules/logic-business/Sources/Functions/ConfigLogic+Extensions.swift, Modules/logic-business/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Sources/Config/WalletKitConfig.swift, Modules/logic-core/Sources/DI/LogicCoreAssembly.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift, Wallet/Config/WalletDemo.xcconfig, Wallet/Config/WalletDemoRelease.xcconfig, Wallet/Config/WalletDev.xcconfig, Wallet/Config/WalletDevRelease.xcconfig, Wallet/Wallet.plist, wiki/configuration.md
Refactored configuration mechanism for RQES and Kit
=> Refactored configuration mechanism for RQES and Kit

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-business/Package.swift, Modules/logic-business/Sources/Config/RQESConfig.swift, wiki/configuration.md
=> Sync with latest RQES SDK

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-common/Sources/UI/Request/BaseRequestView.swift, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-login/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Sources/Interactor/PresentationInteractor.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Sources/Interactor/ProximityInteractor.swift, Modules/feature-proximity/Tests/Interactor/TestProximityInteractor.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/feature-test/Sources/Utils/Constants.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-business/Sources/Extension/Array+Extensions.swift, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Extension/RequestItem+Extensions.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift, Wallet/Wallet.plist
Fixed ui issue with presentation screen on already used presentation request, updated to walletKit 0.7.7
=> Fixed ui issue with presentation screen on already used presentation request, updated to walletKit 0.7.7

wiki/how_to_build.md
=> [fix] update how to build wiki

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-business/Package.swift
=> Updated to latest RQES SDK

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-business/Package.swift, Modules/logic-business/Sources/Config/RQESConfig.swift
=> update to latest RQESSDK

fastlane/Fastfile, fastlane/README.md
Added support to upload tags to EU repo as well on demo release
=> Added support to upload tags to EU repo as well on demo release

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-business/Package.swift
=> Updated RQES Sdk

fastlane/Fastfile
Added package and macro validation exception for tests lane to support CI run
=> Added package and macro validation exception for tests lane to support CI run

fastlane/.xcovignore
Minor correction for xcov rules
=> Minor correction for xcov rules

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-business/Package.swift
=> Updated to Latest RQESKit

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-business/Package.swift
=> new RQES Sdk Version

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-business/Package.swift
=> New RQESUi SDK version

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-test/Sources/Utils/Constants.swift, Modules/logic-business/Package.swift, Modules/logic-core/Package.swift, Modules/logic-ui/Tests/Controller/TestDeepLinkController.swift
New WalletKit and New RQES SDK updates.
=> New WalletKit and New RQES SDK updates.

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> Updated to WalletKit 0.8.4

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> Updated to 0.8.5 WalletKit

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-issuance/Sources/Interactor/DocumentOfferInteractor.swift, Modules/feature-test/Sources/Utils/Constants.swift, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Extension/WalletStorage.Document+Extensions.swift, Modules/logic-core/Sources/Model/DeferrredDocument.swift
=> WalletKit update

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
WalletKit version 0.9.3, Resolved issue with multiple credentials presentation
=> WalletKit version 0.9.3, Resolved issue with multiple credentials presentation

Wallet/Wallet.plist, fastlane/Fastfile, fastlane/README.md
=> Fastlane typo correction

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Reverted swift-certificate package to 1.7.0
=> Reverted swift-certificate package to 1.7.0

Modules/feature-common/Sources/UI/Request/Model/RequestDataUIModel.swift, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Tab/Document/DocumentTabViewModel.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
Fixed presentation issue for mdoc
=> Fixed presentation issue for mdoc

Modules/feature-common/Sources/UI/Request/Model/RequestDataUIModel.swift
Fixed mdoc request creation path calculation
=> Fixed mdoc request creation path calculation

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-proximity/Tests/Interactor/TestProximityInteractor.swift, Modules/logic-core/Package.swift, README.md
=> VP Draft 23 support

Modules/feature-common/Sources/UI/Request/Model/RequestDataUIModel.swift
[Correction for SD-JWT claims with array instead of nested](https://github.com/eu-digital-identity-wallet/eudi-app-ios-wallet-ui/commit/1dfb1e7949b6630da264f2f4752ff20024e82983)
=> Correction for SD-JWT claims with array instead of nested

Modules/feature-common/Sources/UI/Request/Model/RequestDataUIModel.swift, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Sources/UI/Document/Details/Model/DocumentDetailsUIModel.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Interactor/TestProximityInteractor.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
Resolved critical parsing issues for nested SD-JWT and simulated nested mdoc claims
=> Resolved critical parsing issues for nested SD-JWT and simulated nested mdoc claims

Modules/feature-common/Sources/UI/Request/Model/RequestDataUIModel.swift, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Sources/UI/Document/Details/Model/DocumentDetailsUIModel.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-core/Sources/Extension/DocumentElementClaim+Extensions.swift, Modules/logic-ui/Sources/DesignSystem/Component/List/ListItemData.swift, Modules/logic-ui/Sources/Extension/ExpandableListItem+Extensions.swift, Modules/logic-ui/Sources/Extension/ListItemSection+Extensions.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
Added alphabetically sorting for all claims and attributes, minor refactor
=> Added alphabetically sorting for all claims and attributes, minor refactor

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Config/WalletKitConfig.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift
VCI Configuration enhancements, dependencies updates
=> VCI Configuration enhancements, dependencies updates

Modules/logic-business/Sources/Validator/Model/Filters.swift
Resolve filtering logic for multiple sections.
=> Bug fix when apply filters

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> WalletKit Update to 0.10.3

Modules/feature-dashboard/Sources/Interactor/DocumentTabInteractor.swift
apply the issuer filter in documents
=> Bug fix in documents filters

Modules/feature-common/Sources/Config/ScannerUiConfig.swift
Better logging for ScannerUiConfig.Flow
=> Better logging for ScannerUiConfig.Flow

Modules/feature-dashboard/Sources/Router/DashboardRouter.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Tab/Document/DocumentTabViewModel.swift, Modules/feature-dashboard/Sources/UI/IssuanceOption/IssuanceOptionView.swift, Modules/feature-dashboard/Sources/UI/IssuanceOption/IssuanceOptionViewModel.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Sources/UI/Document/Add/AddDocumentView.swift, Modules/logic-ui/Sources/DesignSystem/Button/ButtonViewStyle.swift, Modules/logic-ui/Sources/Navigation/AppRoute.swift
Improvements for feature-dashboard module and WrapButton Styles
=> Improvements for feature-dashboard module and WrapButton Styles

Modules/feature-issuance/Sources/UI/Document/Add/AddDocumentViewModel.swift
Give priority to credential offer deep link on AddDocument Screen when error retrieving issuer scoped documents.
=> Give priority to credential offer deeplink on AddDocument Screen when error retrieving issuer scoped documents.

Modules/feature-dashboard/Tests/Interactor/TestDocumentTabInteractor.swift, Modules/logic-core/Sources/Config/WalletKitConfig.swift, Modules/logic-core/Sources/Model/DocumentIdentifier.swift
=> Updated categories

Modules/feature-issuance/Sources/UI/Document/Add/AddDocumentViewModel.swift
Correction for deepLink and issuance resume process on scoped documents retrieval failure
=> Correction for deepLink and issuance resume process on scoped documents retrieval failure

fastlane/Fastfile
Fastlane: Support for TestFlight external distribution
=> Fastlane: Support for TestFlight external distribution

Modules/feature-common/Sources/UI/Component/AddNewDocumentCellView.swift, Modules/feature-common/Sources/UI/Component/FloatingActionButtonBarView.swift, Modules/logic-ui/Sources/DesignSystem/Component/Wrap/WrapCheckBoxView.swift
=> Minor Corrections

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-business/Package.swift, Modules/logic-core/Package.swift
New WalletKit/RQES/Copyable Versions, Updated all dependencies.
=> New WalletKit/RQES/Copyable Versions, Updated all dependencies.

Modules/feature-presentation/Sources/Interactor/PresentationInteractor.swift, Modules/feature-proximity/Sources/Interactor/ProximityInteractor.swift
Fix for Presentation/Proximity Request
=> Fix for Presentation/Proximity Request

Modules/feature-dashboard/Sources/UI/Detail/Document/Component/RevokedDocumentView.swift
Correction for Revoked Details View
=> Correction for Revoked Details View

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
new WalletKit version to resolve presentation issue for SD-JWT.
=> new WalletKit version to resolve presentation issue for SD-JWT.

Modules/feature-dashboard/Sources/UI/Detail/Transaction/TransactionDetailsView.swift, Modules/logic-ui/Sources/DesignSystem/Component/Wrap/WrapButtonView.swift
Disable Delete and Report Buttons on Transaction Details View
=> Disable Delete and Report Buttons on Transaction Details View

Modules/feature-common/Sources/UI/Biometry/BiometryViewModel.swift, Modules/feature-common/Sources/UI/Loading/BaseLoadingViewModel.swift, Modules/feature-common/Sources/UI/QuickPin/QuickPinViewModel.swift, Modules/feature-common/Sources/UI/Request/BaseRequestViewModel.swift, Modules/feature-common/Sources/UI/Scanner/ScannerView.swift, Modules/feature-common/Sources/UI/Success/Document/DocumentSuccessViewModel.swift, Modules/feature-dashboard/Sources/Interactor/Dashboard/DocumentTabInteractor.swift, Modules/feature-dashboard/Sources/Interactor/Dashboard/TransactionTabInteractor.swift, Modules/feature-dashboard/Sources/UI/Dashboard/DashboardView.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Tab/Document/DocumentTabViewModel.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Tab/Home/HomeTabViewModel.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Tab/Transaction/TransactionTabView.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Tab/Transaction/TransactionTabViewModel.swift, Modules/feature-dashboard/Sources/UI/Detail/Document/DocumentDetailsView.swift, Modules/feature-dashboard/Sources/UI/Detail/Document/DocumentDetailsViewModel.swift, Modules/feature-dashboard/Sources/UI/Detail/Transaction/TransactionDetailsViewModel.swift, Modules/feature-dashboard/Sources/UI/Issuance/IssuanceOptionView.swift, Modules/feature-dashboard/Sources/UI/SideMenu/SideMenuView.swift, Modules/feature-dashboard/Sources/UI/SignDocument/SignDocumentView.swift, Modules/feature-issuance/Sources/UI/Document/Add/AddDocumentViewModel.swift, Modules/feature-issuance/Sources/UI/Document/Code/OfferCodeViewModel.swift, Modules/feature-issuance/Sources/UI/Document/Offer/DocumentOfferView.swift, Modules/feature-issuance/Sources/UI/Document/Offer/DocumentOfferViewModel.swift, Modules/feature-proximity/Sources/UI/Connectivity/ProximityConnectionView.swift, Modules/logic-business/Sources/Validator/FilterValidator.swift, Modules/logic-business/Sources/Validator/Model/Filters.swift, Modules/logic-ui/Sources/DesignSystem/Component/Content/ContentScreenView.swift, Modules/logic-ui/Sources/DesignSystem/Toolbar/ToolBarContent.swift
Resolved issue with Documents/Transactions filtering,  Refactored ContentScreen and added notification centralized capability
=> Resolved issue with Documents/Transactions filtering,  Refactored ContentScreen and added notification centralized capability

Modules/feature-common/Sources/UI/Request/BaseRequestView.swift, Modules/feature-common/Sources/UI/Success/Document/DocumentSuccessView.swift, Modules/feature-dashboard/Sources/UI/Detail/Document/DocumentDetailsView.swift, Modules/feature-dashboard/Sources/UI/Detail/Document/DocumentDetailsViewModel.swift, Modules/feature-dashboard/Sources/UI/Detail/Transaction/Component/TransactionCardView.swift, Modules/feature-dashboard/Sources/UI/Detail/Transaction/Model/TransactionDetailsCardData.swift, Modules/feature-dashboard/Sources/UI/Detail/Transaction/Model/TransactionDetailsUiModel.swift, Modules/feature-dashboard/Sources/UI/Detail/Transaction/TransactionDetailsView.swift, Modules/feature-dashboard/Sources/UI/Detail/Transaction/TransactionDetailsViewModel.swift, Modules/logic-ui/Sources/DesignSystem/Component/List/WrapExpandableListView.swift, Modules/logic-ui/Sources/DesignSystem/Component/List/WrapListItemView.swift, Modules/logic-ui/Sources/DesignSystem/Component/List/WrapListItemsView.swift
transaction details shimmering
=> transaction details shimmering

Modules/feature-dashboard/Sources/Interactor/Dashboard/TransactionTabInteractor.swift
Include the Shared Credentials name for the transactions search
=> Include the Shared Credentials name for the transactions search

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-dashboard/Sources/Interactor/Dashboard/TransactionTabInteractor.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Component/FiltersListView.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Tab/Transaction/TransactionTabView.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Tab/Transaction/TransactionTabViewModel.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Package.swift
New Kit Version, Transactions Date Range filtering corrections
=> New Kit Version, Transactions Date Range filtering corrections

Modules/feature-presentation/Sources/Interactor/PresentationInteractor.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/TestPresentationInteractor.swift
Unit Testing on feature presentation Module 
=> Unit Testing on feature-presentation Module 

Modules/feature-presentation/Tests/TestPresentationInteractor.swift, Modules/feature-proximity/Tests/Interactor/TestProximityInteractor.swift
Rename presentation and proximity interactor tests
=> Rename presentation and proximity interactor tests

Modules/feature-dashboard/Sources/Interactor/Dashboard/DocumentTabInteractor.swift, README.md
Documents List Revoked Filter, disabled by default
=> Documents List Revoked Filter, disabled by default

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> New WalletKit Version (Draft 24 VP)

Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Sources/Controller/SystemBiometryController.swift, Modules/logic-authentication/Tests/Controller/TestPinStorageController.swift, Modules/logic-authentication/Tests/Controller/TestSystemBiometryController.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift
Write Logic authentication unit tests
=> Logic authentication unit tests

Modules/feature-common/Tests/Interactor/TestBiometryInteractor.swift, Modules/feature-common/Tests/Interactor/TestScannerInteractor.swift
Write unit tests for Biometry and Scanner interactor
=> Feature common unit tests

Modules/logic-authentication/Sources/Controller/SystemBiometryController.swift
Add a description of the change here
=> Adds error descriptions for biometry failures

Modules/feature-presentation/Tests/Interactor/TestPresentationInteractor.swift, Modules/feature-proximity/Tests/Interactor/TestProximityInteractor.swift, Modules/logic-authentication/Tests/Controller/TestSystemBiometryController.swift
Unit tests for logic authentication, feature presentation and feature proximity packages
=> Add more unit tests for coverage

Modules/logic-core/Sources/Config/WalletKitConfig.swift
=> Fix for PDA1 categorization

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-core/Sources/Model/DeferrredDocument.swift
=> New WalletKit Version 0.12.7

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/feature-common/Tests/Mock/GeneratedMocks.swift, Modules/feature-dashboard/Sources/Interactor/Dashboard/DocumentTabInteractor.swift, Modules/feature-dashboard/Sources/Interactor/Detail/DocumentDetailsInteractor.swift, Modules/feature-dashboard/Tests/Interactor/TestDocumentDetailsInteractor.swift, Modules/feature-dashboard/Tests/Interactor/TestDocumentTabInteractor.swift, Modules/feature-dashboard/Tests/Interactor/TestHomeTabInteractor.swift, Modules/feature-dashboard/Tests/Mock/GeneratedMocks.swift, Modules/feature-issuance/Tests/Interactor/TestAddDocumentInteractor.swift, Modules/feature-issuance/Tests/Interactor/TestDocumentOfferInteractor.swift, Modules/feature-issuance/Tests/Mock/GeneratedMocks.swift, Modules/feature-presentation/Tests/Mock/GeneratedMocks.swift, Modules/feature-proximity/Tests/Mock/GeneratedMocks.swift, Modules/feature-startup/Tests/Interactor/TestStartupInteractor.swift, Modules/feature-startup/Tests/Mock/GeneratedMocks.swift, Modules/feature-test/Sources/Utils/Constants.swift, Modules/logic-api/Tests/Mock/GeneratedMocks.swift, Modules/logic-authentication/Tests/Mock/GeneratedMocks.swift, Modules/logic-core/Package.swift, Modules/logic-core/Sources/Config/WalletKitConfig.swift, Modules/logic-core/Sources/Controller/WalletKitController.swift, Modules/logic-ui/Tests/Controller/TestDeepLinkController.swift, Modules/logic-ui/Tests/Mock/GeneratedMocks.swift
=> Sync with latest WalletKit

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> WalletKit update 0.12.9, dpop fix, new SD-JWT library version

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> Dependency updates

Modules/feature-issuance/Sources/UI/Document/Add/AddDocumentViewModel.swift
Updates scanner footer visibility logic
=> Updates scanner footer visibility logic

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, fastlane/Fastfile, fastlane/README.md
Add a description of the change here
=> Dependencies updates, minor fastlane typos

Modules/feature-common/Sources/Extension/DocClaimsDecodable+Extensions.swift, Modules/feature-common/Sources/UI/Request/BaseRequestView.swift, Modules/feature-common/Sources/UI/Request/Model/RequestDataUIModel.swift, Modules/feature-common/Sources/UI/Success/Document/DocumentSuccessView.swift, Modules/feature-dashboard/Sources/Extension/DocumentUIModel+Extensions.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Model/DocumentTabUIModel.swift, Modules/feature-dashboard/Sources/UI/Dashboard/Model/TransactionTabUIModel.swift, Modules/feature-dashboard/Sources/UI/Detail/Transaction/Component/TransactionDetailsListItemsView.swift, Modules/feature-dashboard/Sources/UI/Detail/Transaction/TransactionDetailsView.swift, Modules/feature-dashboard/Sources/UI/SignDocument/SignDocumentView.swift, Modules/feature-dashboard/Sources/UI/SignDocument/SignDocumentViewModel.swift, Modules/feature-dashboard/Tests/Interactor/TestDocumentTabInteractor.swift, Modules/feature-issuance/Sources/Interactor/AddDocumentInteractor.swift, Modules/feature-issuance/Sources/UI/Document/Add/Model/AddDocumentUIModel.swift, Modules/feature-issuance/Sources/UI/Document/Offer/Component/DocumentOfferCellView.swift, Modules/feature-issuance/Sources/UI/Document/Offer/Model/DocumentOfferUIModel.swift, Modules/feature-issuance/Tests/Interactor/TestDocumentOfferInteractor.swift, Modules/feature-presentation/Tests/Interactor/TestPresentationInteractor.swift, Modules/feature-proximity/Tests/Interactor/TestProximityInteractor.swift, Modules/logic-ui/Sources/DesignSystem/Component/List/ExpandableCardView.swift, Modules/logic-ui/Sources/DesignSystem/Component/List/ListItemData.swift, Modules/logic-ui/Sources/DesignSystem/Component/List/WrapExpandableListView.swift, Modules/logic-ui/Sources/DesignSystem/Component/List/WrapListItemView.swift, Modules/logic-ui/Sources/DesignSystem/Component/List/WrapListItemsView.swift, Modules/logic-ui/Sources/DesignSystem/Component/SearchableList/SearchableListView.swift
The signature field name is displayed in incorrect position on the attestation.
=> Fix Signature field alignment issue

Wallet/Application.swift
=> Correction for iOS 17

EudiReferenceWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Modules/logic-core/Package.swift
=> Updated WalletKit

fastlane/Fastfile
=> Removed external destribution for fastlane pilot
